user_admin:
  path:   /user
  defaults:
    _controller: AdminBundle:Admin:user

category_admin:
  path:   /category
  defaults:
    _controller: AdminBundle:Admin:category

product_admin:
  path:   /product
  defaults:
    _controller: AdminBundle:Admin:product
index_admin:
  path:   /
  defaults:
    _controller: AdminBundle:Admin:index






add_new_produit:
  path:   /add
  defaults:
    _controller: AdminBundle:Admin:addProduct

remove_produit:
  path:   /remove
  defaults:
    _controller: AdminBundle:Admin:removeProduct
