routingProduits:
  resource: "@ECommBundle/Resources/config/routing/routingProduct.yml"
  prefix: /product

routingPage:
  resource: "@ECommBundle/Resources/config/routing/routingPage.yml"
  prefix: /

routingSecurity:
  resource: "@ECommBundle/Resources/config/routing/routingSecurity.yml"
  prefix: /

routingPanier:
  resource: "@ECommBundle/Resources/config/routing/routingCart.yml"
  prefix: /cart

routingCommande:
  resource: "@ECommBundle/Resources/config/routing/routingOrder.yml"
  prefix: /order

routingAdmin:
  resource: "@ECommBundle/Resources/config/routing/routingAdmin.yml"
  prefix: /admin
