routingProduits:
  resource: "@ECommBundle/Resources/config/routing/routingProduits.yml"
  prefix: /Produits

routingPage:
  resource: "@ECommBundle/Resources/config/routing/routingPage.yml"
  prefix: /




