panier_produit:
  path:   /
  defaults:
    _controller:  ECommBundle:Panier:panier

add_panier:
  path:   /add
  defaults:
    _controller: ECommBundle:Panier:add

remove_panier:
  path:   /remove/{id}
  defaults:
    _controller: ECommBundle:Panier:remove
  requirements:
      id: \d*

emptypanier_produit:
  path:   /vider
  defaults:
    _controller:  ECommBundle:Panier:emptyPanier
