panier_produit:
  path:   /
  defaults:
    _controller:  ECommBundle:Cart:panier

add_panier:
  path:   /add
  defaults:
    _controller: ECommBundle:Cart:add

remove_panier:
  path:   /remove/{id}
  defaults:
    _controller: ECommBundle:Cart:remove
  requirements:
      id: \d*

emptypanier_produit:
  path:   /vider
  defaults:
    _controller:  ECommBundle:Cart:emptyPanier
