ecomm_home:
    path:      /{page}
    defaults:
        _controller: ECommBundle:Produits:index
        page:        1
    requirements:
        page: \d*

consultation_produit:
  path:   consultation/{id}
  defaults:
      _controller: ECommBundle:Produits:consultation









add_panier:
  path:   /add
  defaults:
      _controller: ECommBundle:Panier:add


panier_produit:
  path:   /panier
  defaults:
    _controller:  ECommBundle:Panier:panier

emptypanier_produit:
  path:   /panier/vider
  defaults:
    _controller:  ECommBundle:Panier:emptyPanier
