ecomm_home:
    path:      /{page}
    defaults:
        _controller: ECommBundle:Produits:index
        page:        1
    requirements:
        page: \d*

consultation_produit:
  path:   consultation/{id}
  defaults:
      _controller: ECommBundle:Produits:consultation


category:
  path:   category/{slug}
  defaults:
      _controller: ECommBundle:Produits:category
