ecomm_home:
    path:      /{page}
    defaults:
        _controller: ECommBundle:Produits:index
        page:        1
    requirements:
        page: \d*

add_produit:
  path:   /add
  defaults:
      _controller: ECommBundle:Produits:add

consultation_produit:
  path:   /consultation/{nomProduit}
  defaults:
      _controller: ECommBundle:Produits:consultation
      nomProduit: ""
  requirements:
      nomProduit: \w*

panier_produit:
  path:   /panier
  defaults:
    _controller:  ECommBundle:Produits:panier

emptypanier_produit:
  path:   /panier/vider
  defaults:
    _controller:  ECommBundle:Produits:emptyPanier
