login:
    path:      /login
    defaults:  { _controller:ECommBundle:Security:login }
logout:
    path: /logout
user_registration:
    path:     /register
    defaults: { _controller: ECommBundle:Security:register }
