ecomm:
    resource: "@ECommBundle/Resources/config/routing.yml"
    prefix:   /platform

# On inclut également les routes de notre CoreBundle, sans préfixe
core:
    resource: "@CoreBundle/Resources/config/routing.yml"
